services:
  remote-gui:
    #image: anylogco/remote-gui:1.0.0-c15f31-amd64
    image: anylogco/remote-gui:latest
    container_name: remote-gui
    restart: always
    stdin_open: true
    hostname: remote-gui
    tty: true
    environment:
      VITE_API_URL: http://127.0.0.1:8080
      # Optional request timeout tuning (seconds)
      # ANYLOG_CONNECT_TIMEOUT: 5
      # ANYLOG_READ_TIMEOUT: 30
      #GRAFANA_URL: http://23.239.12.151:3100/dashboards
    ports:
      - "3000:3000"
      - "31800:31800"
      - "8080:8080"
    volumes:
      - image-vol:/app/CLI/local-cli-backend/static/
      - usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/
      - report-configs:/app/CLI/local-cli-backend/plugins/reportgenerator/templates
#  ollama-node:
#    container_name: ollama
#    image: ollama/ollama:latest
#    ports:
#      - "11435:11434"
#    volumes:
#      - ollama-data:/root/.ollama

volumes:
  image-vol:
  usr-mgm-vol:
  report-configs:
    #  ollama-data:


